### ISSUE TITLE
Add Pydantic response model for `create_database` function

### ISSUE THREAD

**Issue by pythonhubdev** [pythonhubdev/PyNotion#1]
The `create_database` response currently returns the response as a `JSON`. It would be easier to have an option that gets the option from the user to know whether they require the output to be a `JSON `or a `Pydantic Object`

```python
def create_database(json=True):
    .....
    .....
```

based on this the function can return a JSON or a `Pydantic Object`

**Comment by chinmayayy** [comment]
Hey @pythonhubdev I could work upon this. Kindly assign it to me, thanks!

**Comment by pythonhubdev** [comment]
@chinmayayy i have started working on this it's 80% done will add more tasks soon you can work on that. I would be happy to collaborate. Thankyou.

**Comment by pythonhubdev** [comment]
@chinmayayy once pushed you can also work on making the code optimized if possible.

**Comment by chinmayayy** [comment]
Sure, thanks!
