### ISSUE TITLE
A boolean value to determine the return type from database functions.

### ISSUE THREAD

**Issue by pythonhubdev** [pythonhubdev/PyNotion#3]
Add a **config or boolean value** like bool to allow the user to customize the type of the return type of the response (either as a Pydantic model or json) that they need similar to the request payload.

```python
def create_database(json: bool):
    if json:
        return something
    return model
```

Similarly for `query_database` as well.

**Comment by chinmayayy** [comment]
Sure, would love to!

**Comment by pythonhubdev** [comment]
@chinmayayy  Please raise a PR once done. Will review and merge.  Thank you.

**Comment by chinmayayy** [comment]
Would making changes to the database_property_configuration.py file to create a new ResponseConfiguration property be a feasible route? I am trying to understand the whole architecture of the project and what all files would be needing a refactor because of this change.

**Comment by pythonhubdev** [comment]
This would only require a very minor change in the `database.py` file. No other files need to be refactored. we are just giving the user an option to choose what return type they require either as a json or a `pydantic` object.

**Comment by chinmayayy** [comment]
So, like a keyboard user input?

**Comment by pythonhubdev** [comment]
No, while calling the function they have to pass a boolean value

```python
notion_client.create_database(json=True)
```

**Comment by pythonhubdev** [comment]
Any update on this @chinmayayy ?

**Comment by chinmayayy** [comment]
Hey, yes. Just give me some time. I'll make a pr in a day or two. thanks!

**Comment by pythonhubdev** [comment]
Sure @chinmayayy
